# Generated by Django 4.1.3 on 2022-11-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_coutry_shippingaddress_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="is_paid", new_name="isPaid",
        ),
    ]
