# Generated by Django 4.1.3 on 2022-11-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_is_paid_order_ispaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/macbook.jpg", null=True, upload_to=""
            ),
        ),
    ]
